### ISSUE TITLE
errors!

### ISSUE THREAD

**Issue by thedavidmeister** [summerscope/boggle-bash#1]
```
Davids-MacBook-Pro:~ davidmeister$ cd boggle-bash/
Davids-MacBook-Pro:boggle-bash davidmeister$ irb
irb(main):001:0> load boggle.rb
NameError: undefined local variable or method `boggle' for main:Object
	from (irb):1
	from /Applications/MAMP/Library/bin/irb:11:in `<main>'
```

oh no!

**Comment by thedavidmeister** [comment]
certainly interesting that my irb is coming from a MAMP directory, lol

**Comment by summerscope** [comment]
@thedavidmeister this should be fixed with commit i'm just pushing. i borked the instructions. we did it a simpler way. soz you _do_ need to have ruby installed to play this, my bad.
