### ISSUE TITLE
no scores?

### ISSUE THREAD

**Issue by thedavidmeister** [summerscope/boggle-bash#2]
```
Davids-MacBook-Pro:boggle-bash davidmeister$ ruby boggle.rb
+--------------+
|  H  U  W  D  |
|  T  H  O  G  |
|  C  O  A  O  |
|  A  O  I  H  |
+--------------+
cat  
game over, bitches!
```

my game finished but i didn't get any scores :/

**Comment by summerscope** [comment]
ah there's no scoring mechanism yet @thedavidmeister 

all the game does is randomly generate a boggle board for you and then tell you when your timer has finished. more features like scores coming soon.

also - you can't make cat - the letters have to touch (square or diagonals) and you can't reuse them) 

so on that board you could have 

DOG
WOO
HUT

for example :)
